/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;

public class Icalendar {

    private double versao = 2.0;
    private String nomeE;
    private String nomeA;
    private String codigoI = "PT";

    ArrayList<Evento> eventos = new ArrayList<>();

    public Icalendar(String nomeE, String nomeA) {

        this.nomeE = nomeE;
        this.nomeA = nomeA;

    }

    public boolean criarEvento(String sumario, String local, int diaI, int mesI, int anoI, int diaF, int mesF, int anoF,
                               int horaI, int minutoI, int segundoI, int horaF, int minutoF, int segundoF,
                               int frequencia, int intervalo, int diaR, int mesR, int anoR, int horaR, int minutoR,
                               int segundoR, int diaSemana, ArrayList<String> datasExcluidas) {
        
        boolean estado = false;
        Evento e = new Evento();

        estado = e.criarEvento(sumario, local, diaI, mesI, anoI, diaF, mesF, anoF, horaI, minutoI, segundoI, horaF,
                               minutoF, segundoF, frequencia, intervalo, diaR, mesR, anoR, horaR, minutoR,
                               segundoR ,diaSemana, datasExcluidas);

        if (estado == true) {
            eventos.add(e);
            return true;
        } else return false;

    }

    public boolean removerEvento(String uID) {

        boolean estado = false;

        for(Evento elemento: eventos){
            if (elemento.getUid() == uID){
                int posicao = eventos.indexOf(elemento);
                eventos.remove(posicao);
                estado = true;
            }
        }

        return estado;
    }

    public String toString() {


        if (eventos.isEmpty()) {
            return "Sem eventos cadastrados. Você deve ter pelo menos 1 evento cadastrado no calendário!";
        }
         
        String retorno = "BEGIN:VCALENDAR" + "\n" +
                         "VERSION:" + versao + "\n" +
                         "PRODID:-//" + nomeE + "//" + nomeA + "//" + codigoI + "\n" +
                         eventos.toString() +
                         "END:VCALENDAR";
                         
        return retorno;

    }

}